export const mockUserProfile = {
    nin: "12345678901",
    trackingId: "TRACK123456789",
    firstName: "CHUKWUMA",
    lastName: "ADEBAYO",
    middleName: "IBRAHIM",
    maidenName: "N/A",
    phone: "08012345678",
    dob: "1990-05-15",
    gender: "MALE",
    residence: "No. 42 Independence Avenue, Garki, Abuja",
    state: "FCT",
    lga: "Abuja Municipal",
    photo: "https://api.dicebear.com/7.x/avataaars/svg?seed=NINMock",
    issueDate: new Date().toLocaleDateString('en-GB'),
};
